//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\\r\"")]
        public string TransmitTerminationCharacter {
            get {
                return ((string)(this["TransmitTerminationCharacter"]));
            }
            set {
                this["TransmitTerminationCharacter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReiceveDataAutoscrollEnabled {
            get {
                return ((bool)(this["ReiceveDataAutoscrollEnabled"]));
            }
            set {
                this["ReiceveDataAutoscrollEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReceivedDataTimestampEnabled {
            get {
                return ((bool)(this["ReceivedDataTimestampEnabled"]));
            }
            set {
                this["ReceivedDataTimestampEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReceivedDataClearOnConnect {
            get {
                return ((bool)(this["ReceivedDataClearOnConnect"]));
            }
            set {
                this["ReceivedDataClearOnConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Monospac821 BT, 10.2pt")]
        public global::System.Drawing.Font SystemFont {
            get {
                return ((global::System.Drawing.Font)(this["SystemFont"]));
            }
            set {
                this["SystemFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public string Baudrate {
            get {
                return ((string)(this["Baudrate"]));
            }
            set {
                this["Baudrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string DataBits {
            get {
                return ((string)(this["DataBits"]));
            }
            set {
                this["DataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Parity {
            get {
                return ((string)(this["Parity"]));
            }
            set {
                this["Parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string StopBits {
            get {
                return ((string)(this["StopBits"]));
            }
            set {
                this["StopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Handshake {
            get {
                return ((string)(this["Handshake"]));
            }
            set {
                this["Handshake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReceivedDataHexEnabled {
            get {
                return ((bool)(this["ReceivedDataHexEnabled"]));
            }
            set {
                this["ReceivedDataHexEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitData1HexEnabled {
            get {
                return ((bool)(this["TransmitData1HexEnabled"]));
            }
            set {
                this["TransmitData1HexEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitData2HexEnabled {
            get {
                return ((bool)(this["TransmitData2HexEnabled"]));
            }
            set {
                this["TransmitData2HexEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitData3HexEnabled {
            get {
                return ((bool)(this["TransmitData3HexEnabled"]));
            }
            set {
                this["TransmitData3HexEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitData4HexEnabled {
            get {
                return ((bool)(this["TransmitData4HexEnabled"]));
            }
            set {
                this["TransmitData4HexEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitData1TerminateEnabled {
            get {
                return ((bool)(this["TransmitData1TerminateEnabled"]));
            }
            set {
                this["TransmitData1TerminateEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitData2TerminateEnabled {
            get {
                return ((bool)(this["TransmitData2TerminateEnabled"]));
            }
            set {
                this["TransmitData2TerminateEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitData3TerminateEnabled {
            get {
                return ((bool)(this["TransmitData3TerminateEnabled"]));
            }
            set {
                this["TransmitData3TerminateEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitData4TerminateEnabled {
            get {
                return ((bool)(this["TransmitData4TerminateEnabled"]));
            }
            set {
                this["TransmitData4TerminateEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitDataMultiLineTerminateEnabled {
            get {
                return ((bool)(this["TransmitDataMultiLineTerminateEnabled"]));
            }
            set {
                this["TransmitDataMultiLineTerminateEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmittedDataAutoscrollEnabled {
            get {
                return ((bool)(this["TransmittedDataAutoscrollEnabled"]));
            }
            set {
                this["TransmittedDataAutoscrollEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmittedDataClearOnConnectEnabled {
            get {
                return ((bool)(this["TransmittedDataClearOnConnectEnabled"]));
            }
            set {
                this["TransmittedDataClearOnConnectEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmittedDataTimestampEnabled {
            get {
                return ((bool)(this["TransmittedDataTimestampEnabled"]));
            }
            set {
                this["TransmittedDataTimestampEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitData1ClearOnSendEnabled {
            get {
                return ((bool)(this["TransmitData1ClearOnSendEnabled"]));
            }
            set {
                this["TransmitData1ClearOnSendEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitData2ClearOnSendEnabled {
            get {
                return ((bool)(this["TransmitData2ClearOnSendEnabled"]));
            }
            set {
                this["TransmitData2ClearOnSendEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitData3ClearOnSendEnabled {
            get {
                return ((bool)(this["TransmitData3ClearOnSendEnabled"]));
            }
            set {
                this["TransmitData3ClearOnSendEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitData4ClearOnSendEnabled {
            get {
                return ((bool)(this["TransmitData4ClearOnSendEnabled"]));
            }
            set {
                this["TransmitData4ClearOnSendEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransmitDataMultiLineClearOnSendEnabled {
            get {
                return ((bool)(this["TransmitDataMultiLineClearOnSendEnabled"]));
            }
            set {
                this["TransmitDataMultiLineClearOnSendEnabled"] = value;
            }
        }
    }
}
